project_id = "xnunwgrtiffwqhechnwf"

[functions.send-notification-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.chief-chat]
verify_jwt = false

[functions.create-prime-payment]
verify_jwt = false

[functions.prime-payment-webhook]
verify_jwt = false

[functions.create-prime-flutterwave]
verify_jwt = false

[functions.prime-flutterwave-webhook]
verify_jwt = false

[functions.create-prime-stripe]
verify_jwt = false

[functions.prime-stripe-webhook]

[functions.delete-account]
verify_jwt = false
