
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lppgtqtqockemugndxio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwcGd0cXRxb2NrZW11Z25keGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzOTkyOTEsImV4cCI6MjA1ODk3NTI5MX0.XU3emxlOYImEdOWTSqqBi2OOSZN9g6reohd-jnVX_Jo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    '[Supabase] Missing SUPABASE_URL or SUPABASE_PUBLISHABLE_KEY. Please set them in your environment (.env.local, Vercel envs, etc.)'
  );
}
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
