
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnunwgrtiffwqhechnwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhudW53Z3J0aWZmd3FoZWNobndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2MDY4MTgsImV4cCI6MjA4NDE4MjgxOH0.G1OAiQ4XlSi7HtWMpu_ZwDZK7PF57f-6jJNAZfrcucI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    '[Supabase] Missing SUPABASE_URL or SUPABASE_PUBLISHABLE_KEY. Please set them in your environment (.env.local, Vercel envs, etc.)'
  );
}
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
